version: '3.8'

services:
    predman-db:
        image: postgres:15
        container_name: predman-db
        restart: always
        environment:
            - POSTGRES_DB=predman-db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - '5430:5432'
        volumes:
            - db:/var/lib/postgresql/predman
            
volumes:
    db:
        driver: local