version: '3.8'

services:
    predman-db:
        image: postgres:15
        container_name: predman-db
        restart: always
        environment:
            - POSTGRES_DB=predman-db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - '5430:5432'
        volumes:
            - db:/var/lib/postgresql/predman
        networks:
            - predman-network

    predman-content-service:
        image: predman-content-service:latest
        build:
            context: ./Content_Service
            dockerfile: Dockerfile
        container_name: predman-content-service
        depends_on:
            - predman-db
        ports:
            - "8090:8090"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://predman-db/predman-db
            - GRPC_SERVER_HOST=predman-nn-service
            - GRPC_SERVER_PORT=50051
        networks:
            - predman-network

    predman-nn-service:
        image: predman-nn-service:latest
        build:
            context: ./Neural_Network_Service
            dockerfile: Dockerfile
        container_name: predman-nn-service
        depends_on:
            - predman-db
        ports:
            - "50051:50051"
        environment:
            - DATABASE_USER=admin
            - DATABASE_PASSWORD=admin
            - DATABASE_HOST=predman-db
            - DATABASE_PORT=5432
            - DATABASE_NAME=predman-db
        networks:
            - predman-network
    
    client:
        image: predman-client:latest
        container_name: predman-client
        build:
            context: ./Client
            dockerfile: Dockerfile
        ports:
            - 5173:5173
        networks:
            - predman-network

volumes:
    db:
        driver: local

networks:
    predman-network:
        driver: bridge