version: '3.8'

services:
    predman-db:
        image: postgres:15
        container_name: predman-db
        restart: always
        environment:
            - POSTGRES_DB=predman-db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - '5430:5432'
        volumes:
            - db:/var/lib/postgresql/predman
        networks:
            - predman-network

    predman-content-service:
        image: predman-content-service:latest
        build:
            context: ./content
            dockerfile: Dockerfile
        container_name: predman-content-service
        depends_on:
            - predman-db
        ports:
            - "8090:8090"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://predman-db/predman-db
        networks:
            - predman-network
            
volumes:
    db:
        driver: local

networks:
    predman-network:
        driver: bridge